runtime: python39
entrypoint: gunicorn -b :$PORT -k geventwebsocket.gunicorn.workers.GeventWebSocketWorker -w 1 app:app

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: auto

env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: "triple-odyssey-435000-i0-8264176820f3.json"